require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
